### ISSUE TITLE
Users should be able to view blogs individually

### ISSUE THREAD

**Issue by jwoolbright23** [LaunchCodeLiftoffProjects/Collab-Blog#27]
**Is your feature request related to a problem? Please describe.**
Users should have the capability to view each blog individually after created.

**Describe the solution you'd like**
After creating a new blog and viewing all blogs on the homepage, a user should be able to select a blog to view individually.

**Additional context**
Screenshot of what a single blow view may look like
![869c63171476a978c8dfe1fcc16ce3fd](https://user-images.githubusercontent.com/42756773/94026725-a0e11180-fd7f-11ea-8796-b802cc03cd99.png)

**Comment by JonathanCokely** [comment]
I'm interested in working on this one

**Comment by JonathanCokely** [comment]
I created a new component called view-blog using CLI "ng generate component view-blog". I updated the app-routing.module.ts to import the ViewBlogComponent and set a routing path to view-blog. I wrapped the blog-list card in a <a> tag and linked to the new component.html. Up next: creating the view based on the specific blog.

**Comment by JonathanCokely** [comment]
@rrolon47 - Should this issue be considered complete? The only thing not currently displayed in the single blog view is the blog tags.
