### ISSUE TITLE
Users should be able to update blog posts

### ISSUE THREAD

**Issue by jwoolbright23** [LaunchCodeLiftoffProjects/Collab-Blog#28]
**Is your feature request related to a problem? Please describe.**
Users should be able to edit blog posts after they are created

**Describe the solution you'd like**
Create endpoints that allow the user to update blogs

**Additional context**
This is an endpoint that already exists within the BlogController class to display all of the existing blogs as shown below. To update each blog there would need to be a @PostMapping endpoint.

```
@GetMapping("/blogs")
	public List<Blog> getAllBlogs(){
		return blogRepository.findAll();
	}
```

**Comment by elseesea** [comment]
I'd like to work an this as my first foray into this project.
