### ISSUE TITLE
Validation for inputs when making a blog

### ISSUE THREAD

**Issue by rrolon47** [LaunchCodeLiftoffProjects/Collab-Blog#56]
**Is your feature request related to a problem? Please describe.**
If I don't upload an image there is no warning that tell me it is required to submit a blog.  

**Describe the solution you'd like**
Have a warning or alert pop up if there are inputs that are blank after hitting submit.  OR have a button confirming that I don't want to add an input or picture.

**Describe alternatives you've considered**
Allowing blog posts to be published without an image or text.  (that seems a little weird) some type of confirmation I think would be best but open to other ideas. 

**Additional context**

**Comment by JonathanCokely** [comment]
I've been working on this feature. The form type is reactive, which means the validation can occur and display validation messages before the user clicks the submit button.

**Comment by rrolon47** [comment]
@JonathanCokely  Great!  I am moving this to "In Progress"
